import { Geist, Geist_Mono } from 'next/font/google';
import { Poppins } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';

const gtWalsheim = localFont({
  src: [
    {
      path: './fonts/GTWalsheimProRegular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/GTWalsheimProBold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-gt-walsheim',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gtWalsheim.variable}  antialiased`} style={{ fontFamily: 'var(--font-gt-walsheim)' }}>
        {children}
      </body>
    </html>
  );
}
